// Export selected sample decks
export const sampleDecks = {
  "0": {
    "items": [
      "Paladin",
      "Dark Queen Orc",
      "Light Knight Griffin",
      "Potent Grim Drain",
      "Ghoul",
      "Snow Assassin Elf of the Bright Mountains",
      "Dark Monk Ogre of the Polar Woods",
      "Aura Undead Giant of the Low Hills",
      "Nature Age",
      "Fairy",
      "Stun",
      "Light Merchant Hydra",
      "Light Merchant Elf of the Low Hills",
      "Dark Thief Ogre of the Swamp",
      "Shimmering Deathgrip",
      "Frozen Knight Kraken",
      "Dark Grand Demon of Illusion",
      "Troll",
      "Paladin",
      "Light Chaos Demon of the Sky",
      "Snow Lord Orc",
      "Death Grand Demon of the Dead",
      "Spider",
      "Dark Time Dragon of Illusion",
      "Warlock",
      "Cataclysmic Sorrow",
      "Frigid Crown",
      "Light Undead Goblin",
      "Empyrean Hateful Ice",
      "Invert",
      "Empyrean Miracle Helm",
      "Snow Undead Dragon of Hate",
      "Berserker",
      "Light Merchant Griffin",
      "Divine Robe",
      "Troll",
      "Ghoul",
      "Frozen Monk Hydra",
      "Nature Rage",
      "Instant Life Gloves",
      "Instant Miracle Divine Robe",
      "Nimble Drain",
      "Dark Knight Cyclops",
      "Troll",
      "Death Priest Orc"
    ],
    "imageItems": [
      "Paladin",
      "Dark Queen Orc",
      "Light Knight Griffin",
      "Potent Grim Drain",
      "Ghoul",
      "Snow Assassin Elf of the Bright Mountains",
      "Dark Monk Ogre of the Polar Woods",
      "Aura Undead Giant of the Low Hills",
      "Nature Age",
      "Fairy",
      "Stun"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Paladin</tspan><tspan x='32' y='109'>Dark Queen Orc</tspan><tspan x='32' y='127'>Light Knight Griffin</tspan><tspan x='32' y='145'>Potent Grim Drain</tspan><tspan x='32' y='163'>Ghoul</tspan><tspan x='32' y='181'>Snow Assassin Elf of the Bright Mountains</tspan><tspan x='32' y='199'>Dark Monk Ogre of the Polar Woods</tspan><tspan x='32' y='217'>Aura Undead Giant of the Low Hills</tspan><tspan x='32' y='235'>Nature Age</tspan><tspan x='32' y='253'>Fairy</tspan><tspan x='32' y='271'>Stun</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 23 monsters, 3 enchantments,4 spells, 5 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },

  "69": {
    "items": [
      "Troll",
      "Shade",
      "Grim Freeze",
      "Cloak",
      "Skin-Walker",
      "Pandemonium",
      "Grim Pandemonium",
      "Fairy",
      "Tome",
      "Berserker",
      "Chimeric Assault",
      "Maelstrom",
      "Aura Warrior Giant of the Mountains",
      "Fairy",
      "Nimble Drain",
      "Warlock",
      "Flight",
      "Warlock",
      "Ardent Shimmering Lethargy",
      "Frozen Knight Elf of the Golden Palace",
      "Rage",
      "Fairy",
      "Berserker",
      "Cataclysmic Alacrity",
      "Hateful Burn",
      "Paladin",
      "Ardent Frigid Boots",
      "Light Knight Griffin",
      "Frost",
      "Earth Priest Oni of the Polar Woods",
      "Urgent Corpse Reanimate",
      "Burst",
      "Agony",
      "Eagle",
      "Troll",
      "Warlock",
      "Death King Kraken",
      "Gale",
      "Warlock",
      "Sorrow",
      "Berserker",
      "Ghoul",
      "Urgent Nature Gale",
      "Life Blight",
      "Invert"
    ],
    "imageItems": [
      "Troll",
      "Shade",
      "Grim Freeze",
      "Cloak",
      "Skin-Walker",
      "Pandemonium",
      "Grim Pandemonium",
      "Fairy",
      "Tome",
      "Berserker",
      "Chimeric Assault"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Troll</tspan><tspan x='32' y='109'>Shade</tspan><tspan x='32' y='127'>Grim Freeze</tspan><tspan x='32' y='145'>Cloak</tspan><tspan x='32' y='163'>Skin-Walker</tspan><tspan x='32' y='181'>Pandemonium</tspan><tspan x='32' y='199'>Grim Pandemonium</tspan><tspan x='32' y='217'>Fairy</tspan><tspan x='32' y='235'>Tome</tspan><tspan x='32' y='253'>Berserker</tspan><tspan x='32' y='271'>Chimeric Assault</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 17 monsters, 7 enchantments,10 spells, 1 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
  "420": {
    "items": [
      "Haste",
      "Solar Greaves",
      "Berserker",
      "Troll",
      "Grim Invert",
      "Stricken",
      "Death Lord Goblin",
      "Earth Time Phoenix of the Shadows",
      "Paladin",
      "Earth Undead Phoenix of the Shadows",
      "Berserker",
      "Berserker",
      "Troll",
      "Spider",
      "Age",
      "Light Rogue Cyclops",
      "Aura Undead Dragon of the Light",
      "Necro Deathgrip",
      "Burst",
      "Warlock",
      "Gale",
      "Magi",
      "Victory Drain",
      "Snow Undead Orc",
      "Stun",
      "Invert",
      "Berserker",
      "Troll",
      "Shade",
      "Wolf",
      "Paladin",
      "Death Merchant Elf of the West",
      "Magi",
      "Light Nameless Dragon of the Sky",
      "Aura Lord Hydra",
      "Empyrean Lunar Firebreath",
      "Paladin",
      "Pandemonium",
      "Flight",
      "Urgent Forged Agony",
      "Sigil",
      "Oblivion Drain",
      "Assault",
      "Death Ancient Demon of the Dead",
      "Vortex"
    ],
    "imageItems": [
      "Haste",
      "Solar Greaves",
      "Berserker",
      "Troll",
      "Grim Invert",
      "Stricken",
      "Death Lord Goblin",
      "Earth Time Phoenix of the Shadows",
      "Paladin",
      "Earth Undead Phoenix of the Shadows",
      "Berserker"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Haste</tspan><tspan x='32' y='109'>Solar Greaves</tspan><tspan x='32' y='127'>Berserker</tspan><tspan x='32' y='145'>Troll</tspan><tspan x='32' y='163'>Grim Invert</tspan><tspan x='32' y='181'>Stricken</tspan><tspan x='32' y='199'>Death Lord Goblin</tspan><tspan x='32' y='217'>Earth Time Phoenix of the Shadows</tspan><tspan x='32' y='235'>Paladin</tspan><tspan x='32' y='253'>Earth Undead Phoenix of the Shadows</tspan><tspan x='32' y='271'>Berserker</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 19 monsters, 9 enchantments,6 spells, 1 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
    "888": {
    "items": [
      "Greaves",
      "Earth Ancient Demon of the Shadows",
      "Snow Queen Cyclops",
      "Dire Victory Vortex",
      "Solar Gloves",
      "Sorrow",
      "Frozen Lord Cyclops",
      "Invert",
      "Paladin",
      "Dark Revive",
      "Paladin",
      "Gloves",
      "Light Thief Orc",
      "Berserker",
      "Scythe",
      "Wolf",
      "Ghoul",
      "Ghoul",
      "Magi",
      "Ghoul",
      "Earth Lord Giant of the Polar Woods",
      "Flight",
      "Ghoul",
      "Dark King Goblin",
      "Dire Lunar Belt",
      "Life Pandemonium",
      "Dark King Goblin",
      "Ghoul",
      "Lethargy",
      "Tempest",
      "Vortex",
      "Troll",
      "Agony",
      "Skin-Walker",
      "Invisibility",
      "Wolf",
      "Death Undead Hydra",
      "Paladin",
      "Scythe",
      "Assault",
      "Eagle",
      "Magi",
      "Ghoul",
      "Troll",
      "Helm"
    ],
    "imageItems": [
      "Greaves",
      "Earth Ancient Demon of the Shadows",
      "Snow Queen Cyclops",
      "Dire Victory Vortex",
      "Solar Gloves",
      "Sorrow",
      "Frozen Lord Cyclops",
      "Invert",
      "Paladin",
      "Dark Revive",
      "Paladin"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Greaves</tspan><tspan x='32' y='109'>Earth Ancient Demon of the Shadows</tspan><tspan x='32' y='127'>Snow Queen Cyclops</tspan><tspan x='32' y='145'>Dire Victory Vortex</tspan><tspan x='32' y='163'>Solar Gloves</tspan><tspan x='32' y='181'>Sorrow</tspan><tspan x='32' y='199'>Frozen Lord Cyclops</tspan><tspan x='32' y='217'>Invert</tspan><tspan x='32' y='235'>Paladin</tspan><tspan x='32' y='253'>Dark Revive</tspan><tspan x='32' y='271'>Paladin</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 22 monsters, 3 enchantments,5 spells, 5 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
    "111": {
    "items": [
      "Firebreath",
      "Magi",
      "Lightning",
      "Potent Gloom Shrink",
      "Life Assault",
      "Wall",
      "Lunar Alacrity",
      "Mighty Corpse Sigil",
      "Assault",
      "Heal",
      "Dark Ancient Demon of Illusion",
      "Empyrean Necro Helm",
      "Berserker",
      "Skin-Walker",
      "Alacrity",
      "Paladin",
      "Revive",
      "Wolf",
      "Stun",
      "Skin-Walker",
      "Frozen Queen Elf of the Swamp",
      "Earth Priest Hydra",
      "Fairy",
      "Oblivion Helm",
      "Aura Fighter Goblin",
      "Dark Assassin Griffin",
      "Spider",
      "Shrink",
      "Death Knight Cyclops",
      "Alacrity",
      "Flight",
      "Flight",
      "Clever Nimble Haste",
      "Warlock",
      "Miracle Pandemonium",
      "Paladin",
      "Wolf",
      "Wolf",
      "Eagle",
      "Death Lord Cyclops",
      "Life Maelstrom",
      "Maelstrom",
      "Reanimate",
      "Shrink",
      "Troll"
    ],
    "imageItems": [
      "Firebreath",
      "Magi",
      "Lightning",
      "Potent Gloom Shrink",
      "Life Assault",
      "Wall",
      "Lunar Alacrity",
      "Mighty Corpse Sigil",
      "Assault",
      "Heal",
      "Dark Ancient Demon of Illusion"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Firebreath</tspan><tspan x='32' y='109'>Magi</tspan><tspan x='32' y='127'>Lightning</tspan><tspan x='32' y='145'>Potent Gloom Shrink</tspan><tspan x='32' y='163'>Life Assault</tspan><tspan x='32' y='181'>Wall</tspan><tspan x='32' y='199'>Lunar Alacrity</tspan><tspan x='32' y='217'>Mighty Corpse Sigil</tspan><tspan x='32' y='235'>Assault</tspan><tspan x='32' y='253'>Heal</tspan><tspan x='32' y='271'>Dark Ancient Demon of Illusion</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 20 monsters, 7 enchantments,6 spells, 2 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
  "1111": {
    "items": [
      "Dark Ancient Demon of Illusion",
      "Empyrean Necro Helm",
      "Berserker",
      "Skin-Walker",
      "Alacrity",
      "Paladin",
      "Revive",
      "Wolf",
      "Stun",
      "Skin-Walker",
      "Necro Ice",
      "Light Knight Kraken",
      "Wall",
      "Miracle Ghost Wand",
      "Magi",
      "Warlock",
      "Age",
      "Solar Age",
      "Berserker",
      "Berserker",
      "Warlock",
      "Clever Hateful Pandemonium",
      "Death Warrior Griffin",
      "Fairy",
      "Troll",
      "Alacrity",
      "Aura Assassin Giant of the Arctic Blizzards",
      "Magi",
      "Fairy",
      "Aura Grand Demon of the Light",
      "Troll",
      "Fairy",
      "Tempest",
      "Strength",
      "Solar Fireball",
      "Earth Knight Hydra",
      "Deathgrip",
      "Troll",
      "Snow King Ogre of the Polar Woods",
      "Burn",
      "Troll",
      "Berserker",
      "Wolf",
      "Urgent Sorrow Maelstrom",
      "Paladin"
    ],
    "imageItems": [
      "Dark Ancient Demon of Illusion",
      "Empyrean Necro Helm",
      "Berserker",
      "Skin-Walker",
      "Alacrity",
      "Paladin",
      "Revive",
      "Wolf",
      "Stun",
      "Skin-Walker",
      "Necro Ice"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Dark Ancient Demon of Illusion</tspan><tspan x='32' y='109'>Empyrean Necro Helm</tspan><tspan x='32' y='127'>Berserker</tspan><tspan x='32' y='145'>Skin-Walker</tspan><tspan x='32' y='163'>Alacrity</tspan><tspan x='32' y='181'>Paladin</tspan><tspan x='32' y='199'>Revive</tspan><tspan x='32' y='217'>Wolf</tspan><tspan x='32' y='235'>Stun</tspan><tspan x='32' y='253'>Skin-Walker</tspan><tspan x='32' y='271'>Necro Ice</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 22 monsters, 5 enchantments,7 spells, 1 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
  "1001": {
    "items": [
      "Tome",
      "Eagle",
      "Troll",
      "Magi",
      "Firebreath",
      "Strength",
      "Warlock",
      "Necro Ring",
      "Paladin",
      "Crown",
      "Berserker",
      "Dire Chimeric Firebreath",
      "Clever Hateful Assault",
      "Aura Fighter Hydra",
      "Spider",
      "Dark Assassin Elf of the Low Hills",
      "Heal",
      "Victory Potion",
      "Magi",
      "Fairy",
      "Sorrow Stun",
      "Eagle",
      "Warlock",
      "Earth Thief Hydra",
      "Shade",
      "Aura Fighter Goblin",
      "Dark Ancient Demon of Illusion",
      "Ghoul",
      "Eagle",
      "Dark Thief Griffin",
      "Spider",
      "Aura Fighter Griffin",
      "Fairy",
      "Maelstrom",
      "Shield",
      "Light Knight Ogre of the Frozen Castle",
      "Instant Grim Drain",
      "Tome",
      "Ghoul",
      "Frozen Knight Hydra",
      "Spider",
      "Shimmering Amulet",
      "Infuriate",
      "Death Ancient Wizard of the Dead",
      "Earth Assassin Orc"
    ],
    "imageItems": [
      "Tome",
      "Eagle",
      "Troll",
      "Magi",
      "Firebreath",
      "Strength",
      "Warlock",
      "Necro Ring",
      "Paladin",
      "Crown",
      "Berserker"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Tome</tspan><tspan x='32' y='109'>Eagle</tspan><tspan x='32' y='127'>Troll</tspan><tspan x='32' y='145'>Magi</tspan><tspan x='32' y='163'>Firebreath</tspan><tspan x='32' y='181'>Strength</tspan><tspan x='32' y='199'>Warlock</tspan><tspan x='32' y='217'>Necro Ring</tspan><tspan x='32' y='235'>Paladin</tspan><tspan x='32' y='253'>Crown</tspan><tspan x='32' y='271'>Berserker</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 23 monsters, 4 enchantments,5 spells, 3 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
  "1640": {
    "items": [
      "Snow Time Phoenix of Hate",
      "Death Time Dragon of the Dead",
      "Light Rogue Dwarf of the Low Hills",
      "Ghoul",
      "Wolf",
      "Stun",
      "Frozen Assassin Hydra",
      "Frozen King Ogre of the Swamp",
      "Snow Nameless Dragon of Hate",
      "Aura Fighter Kraken",
      "Magi",
      "Invisibility",
      "Spider",
      "Snow King Orc",
      "Ghoul",
      "Eagle",
      "Pandemonium",
      "Fireball",
      "Light Monk Hydra",
      "Light Grand Wizard of the Sky",
      "Aura Monk Kraken",
      "Warlock",
      "Irate Apocalypse Invisibility",
      "Necro Stun",
      "Ardent Victory Gravitation",
      "Nature Cloak",
      "Snow Merchant Hydra",
      "Chimeric Fire",
      "Strength",
      "Dark Merchant Orc",
      "Spider",
      "Dark Lord Orc",
      "Dark Rogue Orc",
      "Frozen Monk Oni of the Black Stone",
      "Warlock",
      "Frozen Queen Kraken",
      "Haste",
      "Dark Priest Oni of the Magical Forest",
      "Grim Stricken",
      "Helmet",
      "Dark Assassin Kraken",
      "Dark Monk Griffin",
      "Dark King Griffin",
      "Light Priest Giant of the Black Stone",
      "Zealous Miracle Alacrity"
    ],
    "imageItems": [
      "Snow Time Phoenix of Hate",
      "Death Time Dragon of the Dead",
      "Light Rogue Dwarf of the Low Hills",
      "Ghoul",
      "Wolf",
      "Stun",
      "Frozen Assassin Hydra",
      "Frozen King Ogre of the Swamp",
      "Snow Nameless Dragon of Hate",
      "Aura Fighter Kraken",
      "Magi"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Snow Time Phoenix of Hate</tspan><tspan x='32' y='109'>Death Time Dragon of the Dead</tspan><tspan x='32' y='127'>Light Rogue Dwarf of the Low Hills</tspan><tspan x='32' y='145'>Ghoul</tspan><tspan x='32' y='163'>Wolf</tspan><tspan x='32' y='181'>Stun</tspan><tspan x='32' y='199'>Frozen Assassin Hydra</tspan><tspan x='32' y='217'>Frozen King Ogre of the Swamp</tspan><tspan x='32' y='235'>Snow Nameless Dragon of Hate</tspan><tspan x='32' y='253'>Aura Fighter Kraken</tspan><tspan x='32' y='271'>Magi</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 22 monsters, 3 enchantments,8 spells, 2 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
    "3340": {
    "items": [
      "Zealous Sorrow Burst",
      "Strength",
      "Warlock",
      "Miracle Ring",
      "Infuriate",
      "Strength",
      "Eagle",
      "Fireball",
      "Earth Grand Demon of the Shadows",
      "Berserker",
      "Paladin",
      "Oblivion Freeze",
      "Dark Undead Dragon of Illusion",
      "Earth Monk Kraken",
      "Reanimate",
      "Light Undead Griffin",
      "Shade",
      "Potent Dark Shrink",
      "Ardent Grim Haste",
      "Aura Thief Elf of the Mountains",
      "Nimble Rage",
      "Frozen King Goblin",
      "Potent Dark Shrink",
      "Dire Dark Vortex",
      "Frozen Ancient Wizard of the Void",
      "Irate Chimeric Alacrity",
      "Light King Griffin",
      "Zealous Lunar Heal",
      "Death Knight Oni of the West",
      "Urgent Frigid Invert",
      "Chimeric Frenzy",
      "Earth Merchant Ogre of the Frozen Castle",
      "Ardent Dark Shield",
      "Ardent Necro Lethargy",
      "Clever Dark Shield",
      "Snow Priest Hydra",
      "Frozen Ancient Wizard of the Void",
      "Gloom Divine Robe",
      "Irate Gloom Burst",
      "Sorrow",
      "Irate Apocalypse Burn",
      "Zealous Necro Deathgrip",
      "Blight",
      "Lethargy",
      "Aura King Elf of the Border"
    ],
    "imageItems": [
      "Zealous Sorrow Burst",
      "Strength",
      "Warlock",
      "Miracle Ring",
      "Infuriate",
      "Strength",
      "Eagle",
      "Fireball",
      "Earth Grand Demon of the Shadows",
      "Berserker",
      "Paladin"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Zealous Sorrow Burst</tspan><tspan x='32' y='109'>Strength</tspan><tspan x='32' y='127'>Warlock</tspan><tspan x='32' y='145'>Miracle Ring</tspan><tspan x='32' y='163'>Infuriate</tspan><tspan x='32' y='181'>Strength</tspan><tspan x='32' y='199'>Eagle</tspan><tspan x='32' y='217'>Fireball</tspan><tspan x='32' y='235'>Earth Grand Demon of the Shadows</tspan><tspan x='32' y='253'>Berserker</tspan><tspan x='32' y='271'>Paladin</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 13 monsters, 12 enchantments,9 spells, 1 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
  "1802": {
    "items": [
      "Ardent Miracle Assault",
      "Divine Robe",
      "Dire Miracle Firebreath",
      "Torment",
      "Sorrow",
      "Aura Assassin Oni of the Black Stone",
      "Fireball",
      "Snow Time Dragon of Hate",
      "Instant Life Assault",
      "Death Queen Griffin",
      "Dark Firebreath",
      "Aura Thief Elf of the Frozen Castle",
      "Boots",
      "Alacrity",
      "Flight",
      "Snow Chaos Demon of Hate",
      "Skin-Walker",
      "Frozen Monk Dwarf of the Mountains",
      "Light Monk Cyclops",
      "Tome",
      "Irate Frigid Wall",
      "Ardent Apocalypse Frost",
      "Earth Grand Demon of the Shadows",
      "Lunar Pandemonium",
      "Clever Apocalypse Sorrow",
      "Vortex",
      "Paladin",
      "Aura Rogue Elf of the Arctic Blizzards",
      "Paladin",
      "Dark Rogue Elf of the Bright Mountains",
      "Urgent Dark Fire",
      "Eagle",
      "Clever Forged Lethargy",
      "Instant Victory Rage",
      "Eagle",
      "Light Nameless Dragon of the Sky",
      "Life Drain",
      "Necro Gloves",
      "Assault",
      "Dire Oblivion Gale",
      "Dark Ancient Demon of Illusion",
      "Aura Fighter Hydra",
      "Zealous Necro Torment",
      "Empyrean Lunar Sorrow",
      "Nimble Heal"
    ],
    "imageItems": [
      "Ardent Miracle Assault",
      "Divine Robe",
      "Dire Miracle Firebreath",
      "Torment",
      "Sorrow",
      "Aura Assassin Oni of the Black Stone",
      "Fireball",
      "Snow Time Dragon of Hate",
      "Instant Life Assault",
      "Death Queen Griffin",
      "Dark Firebreath"
    ],
    "image": "<svg xmlns='http://www.w3.org/2000/svg' preserveAspectRatio='xMinYMin meet' viewBox='0 0 350 350'> <rect width='350' height='350' fill='url(#paint0_linear)'/> <rect width='318' height='318' transform='translate(16 16)' fill='#16150f'/> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' font-weight='bold' letter-spacing='0em'><tspan x='32' y='62.1865'>STARTER DECK</tspan></text> <text fill='#F19100' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='16' font-weight='bold' letter-spacing='0.16em'><tspan x='32' y='43.582'>45 ADVENTURE CARDS</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='12' letter-spacing='0em'><tspan x='32' y='91'>Ardent Miracle Assault</tspan><tspan x='32' y='109'>Divine Robe</tspan><tspan x='32' y='127'>Dire Miracle Firebreath</tspan><tspan x='32' y='145'>Torment</tspan><tspan x='32' y='163'>Sorrow</tspan><tspan x='32' y='181'>Aura Assassin Oni of the Black Stone</tspan><tspan x='32' y='199'>Fireball</tspan><tspan x='32' y='217'>Snow Time Dragon of Hate</tspan><tspan x='32' y='235'>Instant Life Assault</tspan><tspan x='32' y='253'>Death Queen Griffin</tspan><tspan x='32' y='271'>Dark Firebreath</tspan></text> <text fill='white' xml:space='preserve' style='white-space: pre;' font-family='Georgia' font-size='8' letter-spacing='0em'><tspan x='32' y='308.291'>34 other cards: 15 monsters, 5 enchantments,12 spells, 3 artifacts</tspan></text><defs> <linearGradient id='paint0_linear' x1='175' y1='350' x2='175' y2='0' gradientUnits='userSpaceOnUse'> <stop stop-color='#744500'/> <stop offset='1' stop-color='#D68103'/> </linearGradient> </defs></svg>"
  },
}
